### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by msaulohenrique** [VinaBB/VinaBB.vn#1]
[Sat Jan 14 21:14:05.750951 2017] [:error] [pid 3784:tid 1324] [client ::1:10820] PHP Fatal error:  Arrays are not allowed in class constants in C:\\USBWebserver v8.6\\root\\phpBB32\\ext\\vinabb\\web\\includes\\constants.php on line 33

**Comment by nedka** [comment]
Hi msaulohenrique, thanks you for using and testing our website code. You need PHP 5.6+ to run this code, because since PHP 5.6, you can declare an array constant with `const`.

**Comment by msaulohenrique** [comment]
True, he'd forgotten about that rule.
Grateful!
